CREATE DATABASE SARAVIA
GO
USE SARAVIA
GO

CREATE TABLE Customer(
	CustomerID CHAR(6) PRIMARY KEY CHECK(CustomerID LIKE 'CTR[0-9][0-9][0-9]'),
	CustomerName VARCHAR(50) NOT NULL,
	CustomerGender VARCHAR(6) NOT NULL,
	CustomerDOB DATE NOT NULL,
	CustomerPhoneNumber CHAR(12) NOT NULL CHECK(LEN(CustomerPhoneNumber)=12),
	CustomerAddress VARCHAR(50) NOT NULL
)

CREATE TABLE Staff(
	StaffID CHAR(6) PRIMARY KEY CHECK(StaffID LIKE 'STF[0-9][0-9][0-9]'),
	StaffName VARCHAR(50) NOT NULL CHECK(LEN(StaffName) >=3),
	StaffGender VARCHAR(6) NOT NULL CHECK(StaffGender LIKE 'Male' OR StaffGender LIKE 'Female'),
	StaffDOB DATE NOT NULL,
	StaffPhoneNumber CHAR(12) NOT NULL,
	StaffAddress VARCHAR(50) NOT NULL,
	StaffSalary INT NOT NULL
)

CREATE TABLE PenMaterial(
	PenMaterialID CHAR(6) PRIMARY KEY CHECK(PenMaterialID LIKE 'PML[0-9][0-9][0-9]'),
	PenMaterialName VARCHAR(50) NOT NULL,
	PenMaterialPrice INT NOT NULL,
	PenMaterialStock INT CHECK(PenMaterialStock >=100)
)

CREATE TABLE Pen(
	PenID CHAR(6) PRIMARY KEY CHECK(PenID LIKE 'PEN[0-9][0-9][0-9]'),
	PenName VARCHAR(50) NOT NULL CHECK(PenName LIKE '% Pen'),
	PenPrice INT NOT NULL CHECK(PenPrice BETWEEN 10000 AND 50000),
	PenStock INT NOT NULL,
	PenMaterialID CHAR(6) FOREIGN KEY REFERENCES PenMaterial(PenMaterialID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL
)

CREATE TABLE Sales(
	SalesID CHAR(6) PRIMARY KEY CHECK(SalesID LIKE 'SLT[0-9][0-9][0-9]'),
	CustomerID CHAR(6) FOREIGN KEY REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	StaffID CHAR(6) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	SalesDate DATE CHECK(YEAR(SalesDate)=2020),
	PaymentType VARCHAR(10),
	SalesQuantity INT,
)

CREATE TABLE SalesDetail(
	SalesDetailID CHAR(6) PRIMARY KEY CHECK(SalesDetailID LIKE 'SDT[0-9][0-9][0-9]'),
	SalesID CHAR(6) FOREIGN KEY REFERENCES Sales(SalesID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PenID CHAR(6) FOREIGN KEY REFERENCES Pen(PenID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	
	PenQuantity INT NOT NULL
)


CREATE TABLE Vendor(
	VendorID CHAR(6) PRIMARY KEY CHECK(VendorID LIKE 'VDR[0-9][0-9][0-9]'),
	VendorName VARCHAR(50) NOT NULL,
	VendorAddress VARCHAR(50) NOT NULL,
	VendorPhoneNumber CHAR(12) NOT NULL,
	VendorEmail VARCHAR(50) NOT NULL CHECK(VendorEmail LIKE '%@%')
)

CREATE TABLE Purchase(
	PurchaseID CHAR(6) PRIMARY KEY CHECK(PurchaseID LIKE 'PCT[0-9][0-9][0-9]'),
	StaffID CHAR(6) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PurchaseDate DATE NOT NULL,
	PaymentType VARCHAR(10) NOT NULL,
	PurchaseQuantity INT
)

CREATE TABLE PurchaseDetail(
	PurchaseDetailID CHAR(6) PRIMARY KEY CHECK(PurchaseDetailID LIKE 'PDL[0-9][0-9][0-9]'),
	VendorID CHAR(6) FOREIGN KEY REFERENCES Vendor(VendorID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PenMaterialID CHAR(6) FOREIGN KEY REFERENCES PenMaterial(PenMaterialID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PurchaseID CHAR(6) FOREIGN KEY REFERENCES Purchase(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	MaterialQuantity INT NOT NULL
)